//! Fuzzy matching core shared by the lusty front-ends and other consumers
//! (currently the quickshell tray menu, which ports this crate to JS and pins
//! the port with golden vectors — see `lusty --fuzzy-vectors`).
//!
//! Three pieces, all dependency-free:
//!
//! * [`scorer`] — the fzy-style scorer, 1:1 with the Lua port in the nvim
//!   front-end, plus [`scorer::score_with_spans`] for UIs that highlight.
//! * [`rank`] — ordering, the first-letter anchor policy and the RU→EN fallback.
//! * [`layout`] — the RU (йцукен) → EN table.
//! * [`vectors`] — the golden-vector dump used to pin out-of-process ports.
//!
//! Scoring semantics are frozen by [`WEIGHTS_VERSION`]: consumers that cache or
//! compare scores (the JS port and its fixtures) must check it before trusting
//! generated data.

pub mod layout;
pub mod rank;
pub mod scorer;
pub mod vectors;

pub use rank::{rank, Anchor, Layout, Match, RankOpts};
pub use scorer::{match_spans, score, score_with_spans, Scorer};

/// Bump whenever the scoring constants, the span extraction or the ranking
/// order change: golden vectors carry this number and consumers refuse to trust
/// a fixture generated by a different one.
pub const WEIGHTS_VERSION: u32 = 1;
